image: python:3.7-alpine

pages:
  script:
  - pip install sphinx
  - pip install recommonmark
  - sphinx-build -d _build/doctrees . _build/html
  - mv _build/html/ public
  artifacts:
    paths:
    - public
  only:
  - master
