image: python:3.7-alpine

pages:
  script:
  - pip install sphinx
  - pip install recommonmark
  - apk --no-cache add make
  - make html
  - mv _build/html/ public
  artifacts:
    paths:
    - public
  only:
  - master
